# http://mdjnewman.me/2016/01/haskell-stack-yesod-docker/ TODO
image: deepspawn/gtt-blog-exec

pipelines:
  default:
    - step:
        script: 
          - stack --version
          - ls
          - stack exec gtt-blog rebuild --system-ghc
          - aws s3 rm s3://gene-t-taylor.com --recursive
          - aws s3 sync _site s3://gene-t-taylor.com --acl public-read
          - aws configure set preview.cloudfront true
          - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST --paths /\* 